// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkeccqv3GLW3i6qpmLN6XHYoqKyc1VDaI',
    appId: '1:559876578738:web:ae9e0404d0c1dd261518ab',
    messagingSenderId: '559876578738',
    projectId: 'chatting-app-18913',
    authDomain: 'chatting-app-18913.firebaseapp.com',
    storageBucket: 'chatting-app-18913.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmSKk_4BIOEXc2Z7eD72NgbymUDkdCnfw',
    appId: '1:559876578738:android:23f13ddc5f9acbf41518ab',
    messagingSenderId: '559876578738',
    projectId: 'chatting-app-18913',
    storageBucket: 'chatting-app-18913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAttGpOBZTUh-e73KDqUz9x-kqsMMekjTk',
    appId: '1:559876578738:ios:7475f7c50ae207361518ab',
    messagingSenderId: '559876578738',
    projectId: 'chatting-app-18913',
    storageBucket: 'chatting-app-18913.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAttGpOBZTUh-e73KDqUz9x-kqsMMekjTk',
    appId: '1:559876578738:ios:7475f7c50ae207361518ab',
    messagingSenderId: '559876578738',
    projectId: 'chatting-app-18913',
    storageBucket: 'chatting-app-18913.firebasestorage.app',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkeccqv3GLW3i6qpmLN6XHYoqKyc1VDaI',
    appId: '1:559876578738:web:8389874d54c10c9f1518ab',
    messagingSenderId: '559876578738',
    projectId: 'chatting-app-18913',
    authDomain: 'chatting-app-18913.firebaseapp.com',
    storageBucket: 'chatting-app-18913.firebasestorage.app',
  );

}